refactor(test): tests/floodsub - addition of test_factory.rs
LNSD/rust-libp2p-pubsub pull request #144
Opened 2023-09-09 14:44 UTC by Ivansete

Moving implementation of `new_test_topic()` and `new_test_node()` into a separate file: test_factory.rs.

2023-09-10 14:19 UTC, LNSD approved these changes
In general, LGTM ✅ 

Just a tiny nitpicking comment:

> As in the [pubsub-core/tests](https://github.com/LNSD/rust-libp2p-pubsub/tree/main/pubsub-core/tests) directory, the `pubsub_testlib` module is in the root of the directory; I'd rather have a `floodsub_testlib` module in the `/floodsub/tests` directory instead of within a test suite directory.

2023-09-10 23:03 UTC, Ivansete commented
@LNSD - I've applied a different approach. Let me know what do you think about that one :)

2023-09-11 12:03 UTC, LNSD requested changes
Please, check my comments.

2023-09-11 12:03 UTC, LNSD commented on testlib/Cargo.toml
Adding a sub-crate under the tests directory is too much. Additionally, this "local testlib" will clash with the global testlib. 

The lightest option is adding a `floodsub_testlib` module in the `floodsub/tests` directory. And "import it" in each module that uses it (as it suggests the rust test organization documentation: [here](https://doc.rust-lang.org/book/ch11-03-test-organization.html#submodules-in-integration-tests)).

In the future, we may move things to the global `testlib`, but for now, let's keep things local to the crate without additional sub-crates.

2023-09-18 08:41 UTC, LNSD approved these changes

2023-09-18 08:50 UTC, merged